config/routes.rb
Itseasyaspi::Application.routes.draw do
  resources :supplies

  resources :skirtpatterns

  resources :galleries

  resources :userprofiles

  resources :profiles

  devise_for :users

  devise_scope :user do
     match "/users/show" => "devise/registrations#show" 
   end 
  resources :instructions

  resources :comments do
    resources :replies
  end

  get "home/index"

  match '/pattern_maker' => 'home#pattern_maker'
  match '/about' => 'home#about'
  match '/glossary' => 'home#glossary'
  match '/userprofiles' => 'userprofiles#index'
  match '/myprofile' => 'userprofiles#myprofile' 
  match '/step/:id' => 'galleries#step' 

  match '/check', :controller=>'skirtpatterns', :action=>'Usersizes'

  

  root :to => 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :text, :title

  has_many :replies, dependent: :destroy
  
  validates :title,
    presence: true,
    length: { minimum: 5 }
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :image, :step, :submitted_by, :user , :image_comment
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates_presence_of :step, :image_comment , :image
end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  attr_accessible :content, :images, :step, :title
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
  attr_accessible :avatar, :avatar, :bio, :location, :user_id, :website

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :comment
  attr_accessible :body, :comment, :comment_id
end

app/models/skirtpattern.rb
class Skirtpattern < ActiveRecord::Base
  attr_accessible :canvas1, :canvas2, :canvas3, :inner_radius, :length, :makepattern, :outer_radius, :skirt_type, :unit, :user_id, :waist, :waistbandLgth, :waistbandWdth
  
	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
		    csv << column_names
		    all.each do |skirtpattern|
		      csv << skirtpattern.attributes.values_at(*column_names)
		    end
		end
	end
end

app/models/supply.rb
class Supply < ActiveRecord::Base
  attr_accessible :bought, :name

  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me ,:username , :bio , :location , :avatar
  # attr_accessible :title, :body

  mount_uploader :avatar, ImageUploader
  #this handles avatar upload in conjuction with carrierwave
  validates_presence_of :email
   # validates_presence_of :attribute, :on => :create , :message => "can't be black"
  has_one :userprofiles
  has_many :galleries
  has_one :skirtpattern
end

app/models/userprofile.rb
class Userprofile < ActiveRecord::Base
	belongs_to :user
 	attr_accessible :avatar, :bio, :location, :user_id, :username, :website
    mount_uploader :avatar, ImageUploader
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def pattern_maker
          if !current_user then
                  redirect_to "/users/sign_in"
          else
                  @skirtpattern = current_user.build_skirtpattern
          end
  end
end

app/controllers/pattern_controller.rb
class UserprofilesController < ApplicationController

  def update
    @userprofile = Userprofile.find(params[:id])
    respond_to do |format|
      if @userprofile.update_attributes(params[:userprofile])
        format.html { redirect_to @userprofile, notice: 'Userprofile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @userprofile.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  #http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    #require "debugger" ; debugger
    @comment = Comment.find(params[:comment_id])
   #require "debugger" ; debugger
    @reply = @comment.replies.create(reply_params)
    redirect_to comment_path(@comment)
  end

  def destroy
    @comment = Comment.find(params[:comment_id])
    @replies = @comment.replies.find(params[:id])
    @reply.destroy
    redirect_to comment_path(@comment)
  end

  private
    def reply_params
      params.require(:reply).permit(:comment, :body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

def title(page_title)
    content_for (:title) { page_title }
  end

  def yield_or_default(section, default = "")
    content_for?(section) ? content_for(section) : default
  end

 def url_with_protocol(url)
    /^http/.match(url) ? url : "http://#{url}"
  end
end

module UrlHelper
 
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructions_helper.rb
module InstructionsHelper
	def percent 
		# require 'debugger'; debugger
		(@instructions.current_page.to_f / @instructions.total_pages.to_f) * 100
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/skirtpatterns_helper.rb
module SkirtpatternsHelper
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/helpers/userprofiles_helper.rb
module UserprofilesHelper
end

app/views/home/about.html.erb
<h1>About</h1>

app/views/home/glossary.html.erb
<h1>Glossary</h1>

<div class="instructions">
          <section id="Fabric_Bolt">
            <div class="page-header">
              <h1>Fabric Bolt</h1>
            </div>
  
            <p>A bolt is a unit of measurement used as an industry standard for a variety of materials from wood to canvas, typically materials stored in a roll. The length is usually either 40 or 100 yards but varies depending on the fabric being referred to, for example, a bolt of canvas is traditionally 39 yards. The width of such a bolt can also vary. Widths may include 35–36”, 39”, 41”, 44–45”, 50”, 52–54", 58–60” and 66”, 72", 96", and 108".</p>  
          </section>

          <section id="Backstitch">
            <div class="page-header">
                <h1>Backstitch  </h1>
            </div>
         
            <p> Used at the beginning and end of a machine sewn seam to anchor the seam in place; it involves a couple of extra stitches back and forth. (Also known as back tacking.)
           </p>
          </section>
          
          <section id="Baste/basting">
            <div class="page-header">
                <h1>Baste/basting</h1>
            </div>
            <p>Temporary stitching used to hold a sewing project in place and is removed when the permanent sewing is done. </p>
          </section>

          <section id="Bias_tape">
            <div class="page-header">
                <h1>Bias tape</h1>
            </div>
            <p>Strips of fabric cut on the bias, often turned under and pressed, and used for bindings, facings, or other application where there is a need for stretch or accommodation to curves. </p>
          </section>

          <section id="Bobbin">
            <div class="page-header">
                <h1>Bobbin</h1>
            </div>
            <p>The piece of your sewing machine that holds the bottom thread (the bobbin thread) and is placed in the bobbin case. It generally is under the area the needle penetrates and it loops with the needle thread to form a locked stitch.
            </p>
          </section>

          <section id="Bobbin_case">
            <div class="page-header">
                <h1>Bobbin case</h1>
            </div>
            <p>The part of the sewing machine that holds the bobbin. In some machines, it's under the needle plate. Some older machines had them next to the needle plate with a clear lid that slides in order to get to the bobbin.</p>
          </section>

          <section id="Fold_line">
            <div class="page-header">
                <h1>Fold line</h1>
            </div>
            <p>Many pattern pieces are placed on the fold of a piece of fabric. This is the actual fold of the fabric off the bolt or a fold of your own creation; the goal is to have a pattern piece that is cut out without a center seam.
            </p>
          </section>

          <section id="Grain">
            <div class="page-header">
                <h1>Grain</h1>
            </div>
            <p>Direction of the fabric that runs parallel to the selvage (a stretchier grain is found running perpendicular to the selvage). Commercial patterns have an arrow on them &lt;-----&gt; indicating direction of the grain to assist in laying out the pattern pieces correctly.</p>
          </section>

          <section id="Hem">
            <div class="page-header">
                <h1>Hem</h1>
            </div>
            <p>Fabric that it turned up on the lower edge of a garment or sleeve to provide a finished edge. </p>
          </section>

          <section id="Hong_Kong_finish">
            <div class="page-header">
                <h1>Hong Kong finish</h1>
            </div>
            <p>  Enclosing a seam with bias binding. Tutorial off site, which shows exactly how to make and attach the binding</p>
          </section>

          <section id="Interfacing">
            <div class="page-header">
                <h1>Interfacing</h1>
            </div>
            <p>A material (available in a variety of weights/thicknesses/flexibility) used between layers of fabric to provide stabilization and form. Usually used in collars, cuffs, plackets, some waistbands and pockets, and facings. It is available in a fusible or sewn in form. </p>
          </section>

          <section id="Lining">
            <div class="page-header">
                <h1>Lining</h1>
            </div>
            <p>Used to finish the inside of a garment, to hide the seam construction, to allow for ease of putting a garment on or taking it off, and to provide decorative effect. A lining is cut of the same pattern pieces as the garment and often is made of "slippery" fabrics. It provides a minimal amount of warmth and usually extends the life of a garment. Linings should be washable if the garment is washable and should be prewashed.</p>
          </section>

          <section id="Needle">
            <div class="page-header">
                <h1>Needle</h1>
            </div>
            <p>Sewing machine needles come in a variety of sizes and types - ball point and sharps are the two major categories. Ball point is used for knits and regular sharp needles are used for nonstretch fabrics. There are also all purpose needles, but it is recommended that you use ball point or regular rather than all purpose. There are wing needles, wedge needles, needles of varying sizes and shapes, as well as twin needles for some fancier stitching. </p>
          </section>

          <section id="Pattern_weights">
            <div class="page-header">
                <h1>Pattern weights</h1>
            </div>
            <p>Weights used on paper patterns instead of pinning a pattern to the fabric.</p>
          </section>

          <section id="Pins">
            <div class="page-header">
                <h1>Pins</h1>
            </div>
            <p>Pins are used for temporary basting of fabric. They are used to hold patterns in place while cutting and to hold fabrics together while stitching (it is not recommended to machine sew over pins as they have been known to break your sewing machine needle, jam the machine, or cause other problems). Often, large safety pins are used to baste quilt layers before the final quilting. Care should be taken to use a pin that will not leave a large hole and to not leave pins in fabric too long; they could cause stains where they touch the fabric. </p>
          </section>

          <section id="Presser_foot">
            <div class="page-header">
                <h1>Presser foot</h1>
            </div>
            <p>The part of the sewing machine that holds the fabric in place as it is being sewn and fed through by the feed dogs. Specialty feet such as zigzag, buttonhole, cording, blind hem, and others are often included with a sewing machine upon purchase and are best learned by consulting the sewing machine manual.</p>
          </section>

          <section id="Prewashing">
            <div class="page-header">
                <h1>Prewashing</h1>
            </div>
            <p>Prewashing  Washing fabric before using it for a garment or project to allow for any color bleeding and shrinkage. It is best to prewash the fabric as it is to be cleaned and dried when it is in its finished form. (Also known as preshrinking.)</p>
          </section>

          <section id="Raw_Edge">
            <div class="page-header">
                <h1>Raw Edge</h1>
            </div>
            <p>The edge of fabric that is not stitched or finished.</p>
          </section>

          <section id="Rotary_cutter">
            <div class="page-header">
                <h1>Rotary cutter</h1>
            </div>
            <p>Early versions of the rotary cutter looked like pizza cutters. Today, the handles are often ergonomically designed and padded. The blade, though, remains a rounded razor, sometimes with pinked edging or other designs. These are great for cutting layers of fabric into straight strips. Many people are using them for curved lines and pattern cutting for garments as well.</p>
          </section>

          <section id="Seam_allowance">
            <div class="page-header">
                <h1>Seam allowance</h1>
            </div>
            <p>The fabric between the edge of the fabric and the line of stitching, about 5/8" for most patterns. (Craft patterns often allow 1/4" seam allowance.) </p>
          </section>

          <section id="Seam_ripper">
            <div class="page-header">
                <h1>Seam ripper</h1>
            </div>
            <p>Your best friend in the sewing room. It is a tool with a small hook on one end that can slip under a stitch and get close enough to it to cut the stitch. I personally have learned as much about sewing with my seam ripper as I have with making stitches by hand or machine.</p>
          </section>

          <section id="Selvedge">
            <div class="page-header">
                <h1>Selvedge (selvege, selvage)</h1>
            </div>
            <p>Often marked with information from the manufacturer (color code, identifying data, etc.), this is the edge of the fabric which generally does not fray due to manufacturer's finish. In most cases, this edge should not be included when you cut your fabric, as it may cause puckering of your seam later. on. </p>
          </section>

          <section id="Stay_stitch">
            <div class="page-header">
                <h1>Stay stitch</h1>
            </div>
            <p>A line of stitching just inside the intended permanent stitching line (seam line) on curved edges that stabilizes and keeps the curve from distorting. The direction of the stay stitching is shown on the pattern. If not, it generally goes from shoulder to center on necklines. There are other indications for stay stitching, but this is one of the more common. If you do clip curves, use stay stitching first to guide the tip of your scissors - don't cut beyond the stay stitching.</p>
       </section>

          <section id="Stitch_length">
            <div class="page-header">
                <h1>Stitch length</h1>
            </div>
            <p>In general, regular sewing is about 11-12 stitches per inch, basting/gathering/bunching/sleeve easing is about 6 stitches per inch (plus or minus 1 or 2 stitches for some applications). There are rare occasions when stitches need to exceed 12 per inch, but they are few. Stitch length for zigzag is the same as with regular straight stitching; it refers to the number of stitches per inch. The scale varies from machine to machine, so be sure and check your manual. A satin stitch can be created using a zigzag stitch length of zero. </p>
          </section>

          <section id="Top_stitch">
            <div class="page-header">
                <h1>Top stitch</h1>
            </div>
            <p>A sometimes decorative, sometimes functional stitch that is usually 1/4" from the edge of a seam.</p>
          </section>
        </div>

app/views/home/index.html.erb
<!-- Content Slider -->
    <div class="row">
      <div class="large-12 hide-for-small">
        <ul class="example-orbit" data-orbit>
          <li> 
            <%= image_tag("main_1200x500.jpg", :alt => "completed skirt") %> 
            <div class="carousel-caption text-center">
                    <h1>Let's make a skirt!</h1>
                    <p>Want to make an easy to follow custom made pattern, made exactly to your measurements? </p>
                    <p>
                    All you need to do is grab your tape measure and enter your <%= link_to "measurements", pattern_maker_path %> <br>
                    You will whip a circle skirt up in no time following our simple <%= link_to "instructions", instructions_path%>. <br>
                   </p><p> Visit the <%= link_to 'gallery', galleries_path%> to see examples of other users skirts. </p>   
                   <p>It's as easy as Pi!</p>   
            </div>
          </li> 
          <li class="background">
            <div class="carousel-caption text-center">
                    <h2>Watch the video</h2>       
            </div>
            <a href="#" data-reveal-id="videoModal" class="icon-video"></a>
          </li> 
          
      </ul>
    </div>
  </div>
  <!-- End Content Slider -->

  <!-- Mobile Header -->
    <div class="row">
      <div class="large-12 columns show-for-small">
        <%= image_tag("main_510x300.jpg", :alt => "completed skirt") %>
      </div>
    </div><br>

  <!-- End Mobile Header -->
<hr>
<h2 class="text-center">User Gallery</h2>
<h3 class="text-center">Below are user submitted images</h3>

<div class="row"  >
  <div class="large-12 columns">
    <div class="row">
  	<!-- Thumbnails -->
      <div class="large-3 small-6 columns ">
        <a class="fancybox" rel="gallery1" href="/uploads/gallery/image/27/red-felt-circle-skirt.jpg" title="Completed Red Wool Skirt. It swings nicely.">
          <img src="/uploads/gallery/image/27/thumb_med_red-felt-circle-skirt.jpg">
          <h6 class="panel">Completed Red Wool Skirt. It swings nicely.</h6>
        </a>
      </div>

      <div class="large-3 small-6 columns">
        <a class="fancybox" rel="gallery1" href="/uploads/gallery/image/30/Navy_circle_skirt_.JPG" title="Just finished my navy skirt. I am very happy with it.">
          <img src="/uploads/gallery/image/30/thumb_med_Navy_circle_skirt_.JPG">
          <h6 class="panel">Just finished my navy skirt. I am very happy with it.</h6>
        </a>
      </div>

      <div class="large-3 small-6 columns">
         <a class="fancybox" rel="gallery1" href="/uploads/gallery/image/31/cssa_hemclose2.png" title="Rolling the hem on a stretchy red jersey fabric">
          <img src="/uploads/gallery/image/31/thumb_med_cssa_hemclose2.png">
          <h6 class="panel">Rolling the hem on a stretchy red jersey fabric</h6>
         </a>
      </div>

      <div class="large-3 small-6 columns">
         <a class="fancybox" rel="gallery1" href="/uploads/gallery/image/33/hem.jpg" title="Final step - Finishing the hem on my gingham skirt">
          <img src="/uploads/gallery/image/33/thumb_med_hem.jpg">
          <h6 class="panel">Final step - Finishing the hem on my gingham skirt</h6>
         </a>
      </div>
  <!-- End Thumbnails -->
    </div>
  </div>
</div>
<%= link_to 'See More', galleries_path,:class =>"large button expand" %>

<!-- Tour Buttons --> 
<ol class="joyride-list" data-joyride> 
  <li data-id="firstStop" data-text="Next" data-options="tip_location:bottom;tip_animation:fade"> 
    <p>Hello and welcome to easy as pi, watch the video to find more...</p> 
  </li> 
  <li data-id="step1" data-class="custom so-awesome" data-text="Next">  
    <h4>Stop #1</h4> 
    <p>See what other lovely visitors to the site have made.</p> 
  </li> 
  <li data-id="step2" data-button="Next" data-options="tip_location:top;tip_animation:fade"> 
    <h4>Stop #2</h4> 
    <p>Like the look of what you see? Go sign in or go directly to the pattern maker.</p> 
  </li> 
</ol>
<!-- reveal modal begin -->
<div id="videoModal" class="reveal-modal small" data-reveal="" style="display: none; opacity: 1; visibility: hidden;">
  <div class="flex-video" style="display: none;">
          <iframe width="420" height="315" src="about:blank" frameborder="0" allowfullscreen="" data-src="http://www.youtube.com/embed/DRL1QsGw2W8"></iframe>
  </div>
  <a class="close-reveal-modal">×</a>
</div>

<script>
$(document).foundation('joyride', 'start');
</script> 

app/views/home/pattern_maker.html.erb
<%title "Patter Maker"%>
  <!-- start form -->
  <h1><% yield(:title) %></h1>
  <div class="small-8 small-centered columns">
    <div class="content">
    <form id="dress">
      <div id="firstgo">
        <h5>Grab your measuring tape &amp; enter your measurements</h5>
        <h5 class="subheader">( Be honest )</h5>
        <div class="row collapse"> <!-- << this lets form collaspe on resize -->
          <!-- units -->
          <div class="large-2 columns">
            <label class="inline">Units:</label>
          </div>
          <div class="large-10 columns">
              <select id="units" name="units" required="required" class="medium">
                <option value="Centimeters">Centimeters</option>
                <option value="Inches">Inches</option>
              </select>
          </div>
        </div>
        <div class="row collapse">
          <!-- skirt -->
          <div class="large-2 columns">
            <label class="inline">Skirt type:</label>
            <a href="#" data-reveal-id="modal_skirt" class="">?</a>  
          </div>
          <div class="large-10 columns"> 
              <select id="skirt_type" name="skirt_type" required="required" class="medium">
                <option value="full">Full Circle</option>
                <option value="half">Half Circle</option>
              </select>
          </div>
        </div>
        <br>
        <div class="row collapse">
           <!-- Waist -->
          <div class="large-2 columns">
            <label for="waist">Waist: </label>
            <a href="#" data-reveal-id="modal_waist" class="">?</a>          
          </div>
         

          <div class="large-10 columns">
            <input type="number" min="0" id="waist" name="waist" required="required" />
          </div>
        </div>
        <div class="row collapse">
          <!-- Length -->
          <div class="large-2 columns">
              <label for="length">Length: </label>
               <a href="#" data-reveal-id="modal_length" class="">?</a>
          </div>
          <div class="large-10 columns">
             <input type="number"  min="0" id="length" name="length" required="required" />
          </div>
        </div>
        <button type='submit'>Try it</button>
      </div>
        <div id="tryagain" class="hide text-center">
          <a href="#" class="button secondary ">Try again </a>
        </div>
    </form>
    </div>
   </div>
    <!-- end form -->
    <!-- info msg -->
    <div class="row collapse">
      <div class="hide" id="displaymsg">
       <div  class="alert-box text-center large-6 columns">  </div> 
      </div>
      <div id="infomsg" class="hide">
        <table class="large-4 columns right">
          <tr>
            <th colspan="2">Take Note, Important Numbers:</th>
          </tr>
          <tr>
            <td>Waistband Width:</td>
            <td id="waistband_width"</td>
          </tr>
          <tr>
            <td>Waistband Lenght:</td>
            <td id="waistband_lenght"></td>
          </tr>
          <tr>
            <td>Inner Radius:</td>
            <td id="r1" ></td>
          </tr>
          <tr>
            <td>Outer Radius:</td>
            <td id="r2"></td>
          </tr>
        </table> 
      </div>
    </div>
    
    <!-- end info msg --> 
    <hr>
    <!-- start canvas -->
    <div class="hidden">
      <!-- canvas 1 -->
      <div id="c1" class="hide">
        <div class="panel callout text-center">
          <h4>Bolt width 150cm</h4>
          <h5>Length of fabric required:</h5>
          <p id="C1lenght"></p>
        </div>
        <canvas id="Canvas1" width="0" height="0" style="border:1px solid #cccccc;"></canvas><br/>
      </div>
       <!-- canvas 2 -->
      <div id="c2" class="hide">
        <div class="panel callout text-center">
          <h4>Bolt width 115cm</h4>
          <h5>Length of fabric required:</h5>
          <p id="C2lenght"></p>
        </div>
        <canvas id="Canvas2" width="0" height="0" style="border:1px solid #cccccc;"></canvas><br/>
       </div>
       <!-- canvas 3 -->
      <div id="c3" class="hide">
         <div class="panel callout text-center">
            <h4>Bolt width 90cm</h4>
            <h5>Length of fabric required:</h5>
            <p id="C3lenght"></p>
          </div>
        <canvas id="Canvas3" width="0" height="0" style="border:1px solid #cccccc;"></canvas>
        <hr>
      </div>

      <div class="panel callout text-center hide">
        <h4></h4>
        <h5></h5>
        <p> </p>
      </div>
    <div>
      <%= simple_form_for(@skirtpattern) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">

          <%= f.hidden_field :user_id %>
          <%= f.hidden_field :makepattern %>
          <%= f.hidden_field :unit %>
          <%= f.hidden_field :skirt_type %>
          <%= f.hidden_field :waist %>
          <%= f.hidden_field :length %>
          <%= f.hidden_field :canvas1 %>
          <%= f.hidden_field :canvas2 %>
          <%= f.hidden_field :canvas3 %>
          <%= f.hidden_field :inner_radius %>
          <%= f.hidden_field :outer_radius %>
          <%= f.hidden_field :waistbandLgth %>
          <%= f.hidden_field :waistbandWdth %>
        </div>

        <div id="save" class="form-actions hide" >
          <%= f.button :submit, 'Save Pattern' %>
        </div>
      <% end %>
    </div>
    <div id="modal_skirt" class="reveal-modal small" data-reveal="" style="display: none; opacity: 1; visibility: hidden;">
      <p>A full circle skirt is ...</p> 
      <p>A half circle skirt is ...</p> 
      <a class="close-reveal-modal">×</a>
    </div>
    <div id="modal_length" class="reveal-modal small" data-reveal="" style="display: none; opacity: 1; visibility: hidden;">
      <h3>How to determine your skirt length:</h3>
      <p>Start from where you have choosen the waistline to start and end where you want it to finish</p>
      <img src="/uploads/site/measure_info.jpg">
      <a class="close-reveal-modal">×</a>
    </div>
    <div id="modal_waist" class="reveal-modal small" data-reveal="" style="display: none; opacity: 1; visibility: hidden;">
      <h3>How to measure your waist:</h3>
      <img src="/uploads/site/measure_info.jpg">
      <a class="close-reveal-modal">×</a>
    </div>

app/views/replies/_form.html.erb
<%= form_for([@comment, @comment.replies.build]) do |f| %>
  <p>
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
 </p>
  <p>
     <%= f.label :body %><br />
     <%= f.text_area :body %>
   </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/replies/_reply.html.erb
<p>
  <strong>Reply:</strong>
  <%= reply.comment %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= reply.body %>
</p>

<p>
  <%= link_to 'Destroy Reply', [reply.comment, reply],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>