config/routes.rb
Itseasyaspi::Application.routes.draw do
  resources :supplies

  resources :skirtpatterns

  resources :galleries

  resources :userprofiles

  resources :profiles

  devise_for :users

  devise_scope :user do
     match "/users/show" => "devise/registrations#show" 
   end 
  resources :instructions

  resources :comments do
    resources :replies
  end

  get "home/index"

  match '/pattern_maker' => 'home#pattern_maker'
  match '/about' => 'home#about'
  match '/glossary' => 'home#glossary'
  match '/userprofiles' => 'userprofiles#index'
  match '/myprofile' => 'userprofiles#myprofile' 
  match '/step/:id' => 'galleries#step' 

  match '/check', :controller=>'skirtpatterns', :action=>'Usersizes'

  

  root :to => 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :text, :title

  has_many :replies, dependent: :destroy
  
  validates :title,
    presence: true,
    length: { minimum: 5 }
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :image, :step, :submitted_by, :user , :image_comment
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates_presence_of :step, :image_comment , :image
end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  attr_accessible :content, :images, :step, :title
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
  attr_accessible :avatar, :avatar, :bio, :location, :user_id, :website

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :comment
  attr_accessible :body, :comment, :comment_id
end

app/models/skirtpattern.rb
class Skirtpattern < ActiveRecord::Base
  attr_accessible :canvas1, :canvas2, :canvas3, :inner_radius, :length, :makepattern, :outer_radius, :skirt_type, :unit, :user_id, :waist, :waistbandLgth, :waistbandWdth
  
	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
		    csv << column_names
		    all.each do |skirtpattern|
		      csv << skirtpattern.attributes.values_at(*column_names)
		    end
		end
	end
end

app/models/supply.rb
class Supply < ActiveRecord::Base
  attr_accessible :bought, :name

  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me ,:username , :bio , :location , :avatar
  # attr_accessible :title, :body

  mount_uploader :avatar, ImageUploader
  #this handles avatar upload in conjuction with carrierwave
  validates_presence_of :email
   # validates_presence_of :attribute, :on => :create , :message => "can't be black"
  has_one :userprofiles
  has_many :galleries
  has_one :skirtpattern
end

app/models/userprofile.rb
class Userprofile < ActiveRecord::Base
	belongs_to :user
 	attr_accessible :avatar, :bio, :location, :user_id, :username, :website
    mount_uploader :avatar, ImageUploader
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def pattern_maker
          if !current_user then
                  redirect_to "/users/sign_in"
          else
                  @skirtpattern = current_user.build_skirtpattern
          end
  end
end

app/controllers/pattern_controller.rb
class UserprofilesController < ApplicationController

  def update
    @userprofile = Userprofile.find(params[:id])
    respond_to do |format|
      if @userprofile.update_attributes(params[:userprofile])
        format.html { redirect_to @userprofile, notice: 'Userprofile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @userprofile.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  #http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy

  def create
    #require "debugger" ; debugger
    @comment = Comment.find(params[:comment_id])
   #require "debugger" ; debugger
    @reply = @comment.replies.create(reply_params)
    redirect_to comment_path(@comment)
  end

  def destroy
    @comment = Comment.find(params[:comment_id])
    @replies = @comment.replies.find(params[:id])
    @reply.destroy
    redirect_to comment_path(@comment)
  end

  private
    def reply_params
      params.require(:reply).permit(:comment, :body)
    end

end

app/controllers/supplies_controller.rb
class SuppliesController < ApplicationController
  def index
    sleep 1
    @unbought_supplies = Supply.where(bought: false)
    @bought_supplies = Supply.where(bought: true)
  end

  def new
    @supply = Supply.new
  end

  def create
    @supply = Supply.create!(params[:supply])
    #The create method is changed so that the JavaScript format is set to no redirect.
    respond_to do |format|
      format.html {redirect_to supplies_url}
      format.js
    end
  end

  def update
    @supply = Supply.find(params[:id])
    @supply.update_attributes!(params[:supply])
    respond_to do |format|
      format.html {redirect_to supplies_url}
      format.js
    end
  end

  def destroy
    @supply = Supply.destroy(params[:id])
    respond_to do |format|
      format.html {redirect_to supplies_url}
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def title(page_title)
    content_for (:title) { page_title }
  end

  def yield_or_default(section, default = "")
    content_for?(section) ? content_for(section) : default
  end

 def url_with_protocol(url)
    /^http/.match(url) ? url : "http://#{url}"
  end
end

module UrlHelper
 
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructions_helper.rb
module InstructionsHelper
	def percent 
		# require 'debugger'; debugger
		(@instructions.current_page.to_f / @instructions.total_pages.to_f) * 100
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/skirtpatterns_helper.rb
module SkirtpatternsHelper
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/helpers/userprofiles_helper.rb
module UserprofilesHelper
end

app/views/supplies/_form.html.erb
<%= form_for @supply, remote: true do |f| %>
  <%= f.text_field :name %>
  <%=  f.submit "New supply",  :class => "button" %>
<% end %>

app/views/supplies/_supply.html.erb
<%= form_for supply, remote: true do |f| %>
  <%= f.check_box :bought %>
  <%= f.submit "Update" %>
  <%= f.label :bought, supply.name, :class=>"listLabel" %>
  <%= link_to "(remove)", supply, method: :delete, data: {confirm: "Are you sure?"} , remote: true%>
<% end %>

app/views/supplies/create.js.erb
// The create method is changed so that the JavaScript format is set to no redirect. 
// The create.js.erb template is created to handle this. 
$('#new_supply').remove();
$('#new_link').show();
$('#unbought_supplies').append('<%= j render(@supply) %>'); //the new supply is added to the ‘#unbought_supplies’ element.
$('#edit_supply_<%= @supply.id %>').submitOnCheck();// this call the submitOnCheck() from the supplies.js file

app/views/supplies/destroy.js.erb
$('#edit_supply_<%= @supply.id %>').remove();

app/views/supplies/index.html.erb
<h1>Supplies List</h1>
<h2>Before you start sewing, you will need the following items</h2>
<hr>
<div class="row">
  <div class="small-6 columns">
    <h3>Supplies to Gather</h3>
    <div class="supplies" id="unbought_supplies">
        <%= render @unbought_supplies %>
    </div>
  </div>
  <div class="small-6 columns">
    <h3>Supplies Gotten</h3>
    <div class="supplies" id="bought_supplies">
        <%= render @bought_supplies %>
    </div>
  </div>
</div>
<hr>
<p>Have you thought of anything else to add to the list of supplies?</p>
<p>If so add a new supply to the list</p>
<%= link_to "New Supply", new_supply_path, id: "new_link" , :class =>"button secondary", remote: true %>

app/views/supplies/new.html.erb
<h1>New supply</h1>

<%= render 'form' %>

<%= link_to 'Back', supplies_path %>

app/views/supplies/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');
// j method call, escapes ruby data in javaScript

app/views/supplies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @supply.name %>
</p>

<p>
  <b>Bought:</b>
  <%= @supply.bought %>
</p>


<%= link_to 'Edit', edit_supply_path(@supply) %> |
<%= link_to 'Back', supplies_path %>

app/views/supplies/update.js.erb
//The update.js.erb template implements toggling of the supplies from one list to the other.
<% if @supply.bought? %>
	$('#edit_supply_<%= @supply.id %>').appendTo('#bought_supplies');
<% else %>
	$('#edit_supply_<%= @supply.id %>').appendTo('#unbought_supplies');
<% end %>