config/routes.rb
Itseasyaspi::Application.routes.draw do
  resources :supplies

  resources :skirtpatterns

  resources :galleries

  resources :userprofiles

  resources :profiles

  devise_for :users

  devise_scope :user do
     match "/users/show" => "devise/registrations#show" 
   end 
  resources :instructions

  resources :comments do
    resources :replies
  end

  get "home/index"

  match '/pattern_maker' => 'home#pattern_maker'
  match '/about' => 'home#about'
  match '/glossary' => 'home#glossary'
  match '/userprofiles' => 'userprofiles#index'
  match '/myprofile' => 'userprofiles#myprofile' 
  match '/step/:id' => 'galleries#step' 

  match '/check', :controller=>'skirtpatterns', :action=>'Usersizes'

  

  root :to => 'home#index'

end

app/models/skirtpattern.rb
class Skirtpattern < ActiveRecord::Base
  attr_accessible :canvas1, :canvas2, :canvas3, :inner_radius, :length, :makepattern, :outer_radius, :skirt_type, :unit, :user_id, :waist, :waistbandLgth, :waistbandWdth
  
	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
		    csv << column_names
		    all.each do |skirtpattern|
		      csv << skirtpattern.attributes.values_at(*column_names)
		    end
		end
	end
end

app/controllers/skirtpatterns_controller.rb
class SkirtpatternsController < ApplicationController
 # require "Usersizes"
  # GET /skirtpatterns
  # GET /skirtpatterns.json
  def index
    @skirtpatterns = Skirtpattern.order(:id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @skirtpatterns }
      format.csv { render text: @skirtpatterns.to_csv }
    end
  end

  # GET /skirtpatterns/1
  # GET /skirtpatterns/1.json
  def show
    @skirtpattern = Skirtpattern.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @skirtpattern }
    end
  end

  # GET /skirtpatterns/new
  # GET /skirtpatterns/new.json
  def new
    @user = User.find(current_user.id)
    @skirtpattern = Skirtpattern.new
    @skirtpattern.user_id = @user.id

    @skirtpattern.makepattern = 1
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @skirtpattern }
    end
  end

 
  # GET /skirtpatterns/1/edit
  def edit
    @skirtpattern = Skirtpattern.find(params[:id])
  end

  # POST /skirtpatterns
  # POST /skirtpatterns.json
  def create
    #@skirtpattern = Skirtpattern.new(params[:skirtpattern_params])
   # require "debugger" ; debugger
    @skirtpattern = Skirtpattern.new(skirtpattern_params)

    #this Usersizes.addSizing() calls the gem usersizes
    @p1 = Usersizes.addSizing(params[:skirtpattern][:waist],params[:skirtpattern][:length],params[:skirtpattern][:skirt_type])
  
    respond_to do |format|
      if @skirtpattern.save
        format.html { redirect_to @skirtpattern, notice: 'Skirtpattern was successfully saved' }
        format.json { render json: @skirtpattern, status: :created, location: @skirtpattern }
      else
        format.html { render action: "new" }
        format.json { render json: @skirtpattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skirtpatterns/1
  # PATCH/PUT /skirtpatterns/1.json
  def update
    @skirtpattern = Skirtpattern.find(params[:id])

    respond_to do |format|
      if @skirtpattern.update_attributes(skirtpattern_params)
        format.html { redirect_to @skirtpattern, notice: 'Skirtpattern was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @skirtpattern.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skirtpatterns/1
  # DELETE /skirtpatterns/1.json
  def destroy
    @skirtpattern = Skirtpattern.find(params[:id])
    @skirtpattern.destroy

    respond_to do |format|
      format.html { redirect_to skirtpatterns_url }
      format.json { head :no_content }
    end
  end

  private

    # Use this method to whitelist the permissible parameters. Example:
    # params.require(:person).permit(:name, :age)
    # Also, you can specialize this method with per-user checking of permissible attributes.
    def file_name

    end
   
    def skirtpattern_params
      params.require(:skirtpattern).permit(:canvas1, :canvas2, :canvas3, :inner_radius, :length, :makepattern, :outer_radius, :skirt_type, :unit, :user_id, :waist, :waistbandLgth, :waistbandWdth)
    end
end

app/helpers/skirtpatterns_helper.rb
module SkirtpatternsHelper
end

app/views/skirtpatterns/edit.html.erb
<h1>Editing skirtpattern</h1>

<%= render 'form' %>

<%= link_to 'Show', @skirtpattern %> |
<%= link_to 'Back', skirtpatterns_path %>

app/views/skirtpatterns/index.html.erb
<h1>Listing skirtpatterns</h1>

<table>
  <tr>
    <th>User</th>
    <th>Makepattern</th>
    <th>Unit</th>
    <th>Skirt type</th>
    <th>Waist</th>
    <th>Length</th>
    <th>Canvas1</th>
    <th>Canvas2</th>
    <th>Canvas3</th>
    <th>Inner radius</th>
    <th>Outer radius</th>
    <th>Waistbandlgth</th>
    <th>Waistbandwdth</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @skirtpatterns.each do |skirtpattern| %>
  <tr>
    <td><%= skirtpattern.user_id %></td>
    <td><%= skirtpattern.makepattern %></td>
    <td><%= skirtpattern.unit %></td>
    <td><%= skirtpattern.skirt_type %></td>
    <td><%= skirtpattern.waist %></td>
    <td><%= skirtpattern.length %></td>
    <td><%= skirtpattern.canvas1 %></td>
    <td><%= skirtpattern.canvas2 %></td>
    <td><%= skirtpattern.canvas3 %></td>
    <td><%= skirtpattern.inner_radius %></td>
    <td><%= skirtpattern.outer_radius %></td>
    <td><%= skirtpattern.waistbandLgth %></td>
    <td><%= skirtpattern.waistbandWdth %></td>
    <td><%= link_to 'Show', skirtpattern %></td>
    <td><%= link_to 'Edit', edit_skirtpattern_path(skirtpattern) %></td>
    <td><%= link_to 'Destroy', skirtpattern, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Skirtpattern', new_skirtpattern_path %>

app/views/skirtpatterns/new.html.erb
<h1>New skirtpattern</h1>

<%= render 'form' %>

<%= link_to 'Back', skirtpatterns_path %>

app/views/skirtpatterns/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<h1>Your saved pattern </h1>
<div class="row">
  <div class="small-6 columns left">
    <p>
      <b>User:</b>
      <%= @skirtpattern.user_id %>
    </p>

    <p>
      <b>Makepattern:</b>
      <%= @skirtpattern.makepattern %>
    </p>

    <p>
      <b>Unit:</b>
      <%= @skirtpattern.unit %>
    </p>

    <p>
      <b>Skirt type:</b>
      <%= @skirtpattern.skirt_type %>
    </p>

    <p>
      <b>Waist:</b>
      <%= @skirtpattern.waist %>
    </p>

    <p>
      <b>Length:</b>
      <%= @skirtpattern.length %>
    </p>

    <p>
      <b>Canvas1:</b>
      <%= @skirtpattern.canvas1 %>
    </p>

    <p>
      <b>Canvas2:</b>
      <%= @skirtpattern.canvas2 %>
    </p>

    <p>
      <b>Canvas3:</b>
      <%= @skirtpattern.canvas3 %>
    </p>

    <p>
      <b>Inner radius:</b>
      <%= @skirtpattern.inner_radius %>
    </p>

    <p>
      <b>Outer radius:</b>
      <%= @skirtpattern.outer_radius %>
    </p>

    <p>
      <b>Waistbandlgth:</b>
      <%= @skirtpattern.waistbandLgth %>
    </p>

    <p>
      <b>Waistbandwdth:</b>
      <%= @skirtpattern.waistbandWdth %>
    </p>
    </div>
  <div class="small-6 columns right">

    <%= render "shared/advertisment" %>
   
  </div>
</div>
<hr>
<div class="row">
  <%= link_to "Go to Instructions", instructions_path ,:class=> "button" %>
  <%= link_to 'Edit', edit_skirtpattern_path(@skirtpattern),:class=> "button"  %> |
  <%= link_to 'Back', skirtpatterns_path ,:class=> "button" %>
</div>