config/routes.rb
Itseasyaspi::Application.routes.draw do
  resources :supplies

  resources :skirtpatterns

  resources :galleries

  resources :userprofiles

  resources :profiles

  devise_for :users

  devise_scope :user do
     match "/users/show" => "devise/registrations#show" 
   end 
  resources :instructions

  resources :comments do
    resources :replies
  end

  get "home/index"

  match '/pattern_maker' => 'home#pattern_maker'
  match '/about' => 'home#about'
  match '/glossary' => 'home#glossary'
  match '/userprofiles' => 'userprofiles#index'
  match '/myprofile' => 'userprofiles#myprofile' 
  match '/step/:id' => 'galleries#step' 

  match '/check', :controller=>'skirtpatterns', :action=>'Usersizes'

  

  root :to => 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :text, :title

  has_many :replies, dependent: :destroy
  
  validates :title,
    presence: true,
    length: { minimum: 5 }
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :image, :step, :submitted_by, :user , :image_comment
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates_presence_of :step, :image_comment , :image
end

app/models/instruction.rb
class Instruction < ActiveRecord::Base
  attr_accessible :content, :images, :step, :title
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
  attr_accessible :avatar, :avatar, :bio, :location, :user_id, :website

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :comment
  attr_accessible :body, :comment, :comment_id
end

app/models/skirtpattern.rb
class Skirtpattern < ActiveRecord::Base
  attr_accessible :canvas1, :canvas2, :canvas3, :inner_radius, :length, :makepattern, :outer_radius, :skirt_type, :unit, :user_id, :waist, :waistbandLgth, :waistbandWdth
  
	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
		    csv << column_names
		    all.each do |skirtpattern|
		      csv << skirtpattern.attributes.values_at(*column_names)
		    end
		end
	end
end

app/models/supply.rb
class Supply < ActiveRecord::Base
  attr_accessible :bought, :name

  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me ,:username , :bio , :location , :avatar
  # attr_accessible :title, :body

  mount_uploader :avatar, ImageUploader
  #this handles avatar upload in conjuction with carrierwave
  validates_presence_of :email
   # validates_presence_of :attribute, :on => :create , :message => "can't be black"
  has_one :userprofiles
  has_many :galleries
  has_one :skirtpattern
end

app/models/userprofile.rb
class Userprofile < ActiveRecord::Base
	belongs_to :user
 	attr_accessible :avatar, :bio, :location, :user_id, :username, :website
    mount_uploader :avatar, ImageUploader
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def pattern_maker
          if !current_user then
                  redirect_to "/users/sign_in"
          else
                  @skirtpattern = current_user.build_skirtpattern
          end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def title(page_title)
    content_for (:title) { page_title }
  end

  def yield_or_default(section, default = "")
    content_for?(section) ? content_for(section) : default
  end

 def url_with_protocol(url)
    /^http/.match(url) ? url : "http://#{url}"
  end
end

module UrlHelper
 
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructions_helper.rb
module InstructionsHelper
	def percent 
		# require 'debugger'; debugger
		(@instructions.current_page.to_f / @instructions.total_pages.to_f) * 100
	end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/skirtpatterns_helper.rb
module SkirtpatternsHelper
end

app/helpers/supplies_helper.rb
module SuppliesHelper
end

app/helpers/userprofiles_helper.rb
module UserprofilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />
  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Easyaspi - <%= yield_or_default(:title, "Sewing made easy") %></title>
    <%= stylesheet_link_tag  "docs" %>
    <%= stylesheet_link_tag  "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
  	<%= javascript_include_tag "application" %>
    <%= javascript_include_tag "foundation" %>


  	
    <%= csrf_meta_tags %>

	 <script src="http://foundation.zurb.com/docs/assets/js/all.js"></script>

  </head>
  <body>
    <!-- start nav -->
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <h1><%= link_to "Its Easy as Pi", root_path %></a></h1>
        </li>
         <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>
      <section class="top-bar-section">
        <ul class="left">
          <li><%= link_to "Instructions", instructions_path%></li>
          <li class="divider"></li>
          <li><%= link_to "Pattern Maker", pattern_maker_path %></li>
          <li class="divider"></li>
        </ul>

        <ul class="right">
          <li class="divider"></li>
          <!-- Sign in functionality -->
          <% if user_signed_in? %>
            <li id="non-link">Hi, <%= current_user.email%></li>
            <li><%= link_to 'Edit profile', myprofile_path %></li>
             <li class="divider"></li>
              <li class="divider"></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to 'Register', new_user_registration_path %> </li>

            <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>
           <li class="divider"></li>
        </ul>
      </section>
    </nav>
    <!-- end nav -->

    <!-- main content -->
      <div class="row">
        <div class="small-10 small-centered columns">
        	<!-- message -->
          	<div class="small-8 small-centered columns">
		      	 <p id="notice" class="msg notice"><%= notice %></p> 
      			<p id="alert" class="msg notice_error"><%= alert %></p>
      			</div>
		    <%= yield %>
        </div>
    </div>
    <!-- end main content -->
     <!-- Footer -->
    <footer class="row">
      <div class="large-12 columns">
        <hr>
        <div class="row">
          <div class="large-6 columns">
            <p>&copy; Its Easy as Pi 2013</p>
          </div>
          <div class="large-6 columns">
            <ul class="inline-list right">
              <li><%= link_to 'Glossary', glossary_path %></li>
              <li><%= link_to 'About Us', about_path %> </li>
              <li><%= link_to 'Supplies List', supplies_path %> </li>
            </ul>
          </div>
        </div>
      </div>

    </footer>
  <%= javascript_include_tag "global" %>
<script>
// $("#notice:empty").hide();

// $("#alert:empty").hide();

//$("#progress").css("width", "10%");

</script>
	<script>
	   $(document).foundation().foundation('joyride', 'start');
	  </script>
    <script>
    $(document).ready(function() {
  $(".fancybox").fancybox({
    openEffect  : 'none',
    closeEffect : 'none'
  });
});</script>

  </body>
</html>

app/views/shared/_advertisment.html.erb
<ul class="pricing-table">
	<li class="title">Advertisment</li>
 	<li class="price">The Cloth Shop</li>
 	<li class="description">
 		<p>Ireland's best selection of fabric and haberdashery</p>
	 	<ul class="small-block-grid-3"> 
	 		<li><img src="http://www.theclothshop.ie/image/cache/data/velvetgreencitrus-245x190.jpg"><p>Citrus Green Velvet</p></li> 
	 		<li><img src="http://www.theclothshop.ie/image/cache/data/spring/pinkvelvet-265x200.jpg"><p>Hot Pink Velvet</p></li> 
	 		<li><img src="http://www.theclothshop.ie/image/cache/data/spring/gunmetalvelvet-265x200.jpg"><p>Chocolate Brown Velvet</p></a></li> 
	 	</ul>
 </li>
 	<li class="cta-button"><a class="button" href="http://www.theclothshop.ie/" target="_blank">Buy Now</a></li>
</ul>